version: '3'

services:
  db:
    container_name: db
    restart: always
    tty: true
    image: postgres:10
    volumes:
      - database_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database_env
    networks:
      - apps
  web:
    build: .
    container_name: app
    restart: always
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/code
      - static:/code/static  # <-- bind the static volume
    networks:
      - apps
      - nginx_network
    depends_on:
      - db
  nginx:
    image: nginx:1.13
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - nginx_network
networks:
  apps:
    driver: bridge
  nginx_network:
    driver: bridge
volumes:
  database_volume:
  static:
