version: '3'

services:

  # database containers, one for each db
  database:
    image: postgres:10
    volumes:
      - database_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database_env
    networks:
      - database_network

  # web container, with django + gunicorn
  djangoapp:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/djangoapp/src
      - static:/opt/services/djangoapp/static
    ports:
      - "9000:9000"
    networks:
      - database_network
      - nginx_network
    depends_on:
      - database

  # reverse proxy container (nginx)
  nginx:
    image: nginx:1.13
    ports:
      - "8101:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/services/djangoapp/static
    networks:
      - nginx_network
    depends_on:
      - djangoapp

networks:
  database_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  database_volume:
  static:
