swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Django REST API
consumes:
  - application/json
produces:
  - application/json

basePath: /api/v1

# Paths supported by the server application
paths:
  /api/v1/auth/login:
    post:
      operationId: user.login
      tags:
        - Authentication
      summary: Acces for user
      description: User login for authencation
      parameters:
        - name: user
          in: body
          description: user login
          required: True
          schema:
            type: object
            properties:
              username:
                type: string
                description: First name of person to create
              password:
                type: string
                description: Last name of person to create
      responses:
        200:
          description: Successfully created person in list

  /api/v1/auth/logout:
    get:
      operationId: user.logout
      tags:
        - Authentication
      summary: User Logout
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: Bearer JWT Token.
      responses:
        200:
          description: Successfully logout
        401:
          description: Failed to logout

  /people/{lname}:
    get:
      operationId: people.read_one
      tags:
        - People
      summary: Read one person from the people list
      description: Read one person from the people list
      parameters:
        - name: lname
          in: path
          description: Last name of the person to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              timestamp:
                type: string

    put:
      operationId: people.update
      tags:
        - People
      summary: Update a person in the people list
      description: Update a person in the people list
      parameters:
        - name: lname
          in: path
          description: Last name of the person to update in the list
          type: string
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
              lname:
                type: string
      responses:
        200:
          description: Successfully updated person in people list

    delete:
      operationId: people.delete
      tags:
        - People
      summary: Delete a person from the people list
      description: Delete a person
      parameters:
        - name: lname
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a person from people list